### ISSUE TITLE
Broken unicode symbol after minification

### ISSUE THREAD

**Issue by tandu** [ben-eb/cssnano#101]
```css
smile:before {
  content: "\200B";
}
```

is converted to

```css
smile:before {
  content: "200B";
}
```

https://github.com/mgechev/angular2-seed/issues/390
