### ISSUE TITLE
Drop source map comment option

### ISSUE THREAD

**Issue by evilebottnawi** [ben-eb/cssnano#102]
I use cssnano on https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css, and see minify file. In file i found 
```css
...
td,th{padding:0}

/*! Source: https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css */*,:after,:before{-moz-box-sizing:border-box;box-sizing:border-box}html{font-size:10px;-webkit-tap-highlight-color:transparent}body{font-family:Helvetica Neue,Helvetica,Arial,sans-serif;font-size:14px;line-height:1.42857143;color:#222;background-color:#fff}button,input,select,textarea{font-family:inherit;font-size:inherit;line-height:inherit}a{color:#337ab7;text-decoration:none}a:focus,a:hover{color:#23527c;text-decoration:underline}
...
```
