### ISSUE TITLE
border: 0 is removed from output CSS

### ISSUE THREAD

**Issue by davidtheclark** [ben-eb/cssnano#104]
`border: 0;` is being removed from my output CSS. 

If I switch to `border: none`, I can accomplish the same thing and cssnano leaves the `border` declaration alone --- but I believe the removal of `border: 0` is a bug, right?

**Comment by davidtheclark** [comment]
I am using v3.4.0.

**Comment by ben-eb** [comment]
Sounds like it; do you have some example that I could reproduce?

**Comment by davidtheclark** [comment]
I was running into this in a large codebase, and was able to reproduce the problem just by changing the value on and off and checking the output. I will try to figure out a more reduced test case this evening or soon after.

**Comment by ben-eb** [comment]
Can you reproduce with `{mergeRules: false}`?

**Comment by davidtheclark** [comment]
Will give it a try.

**Comment by davidtheclark** [comment]
Yep, your guess is right on: disabling mergeRules avoids the problem. I will try to get a test for that repo.

**Comment by davidtheclark** [comment]
Here is the rule with its adjacent rule:

```css
button {
  background: transparent;
  border: none;
  color: inherit;
  font: inherit;
  margin: 0;
  padding: 0;
  width: auto;
  text-align: left;
  appearance: none;
  user-select: none;
}

button::-moz-focus-inner {
  padding: 0;
  border: 0;
}
```
