### ISSUE TITLE
Plugin to join same keyframes

### ISSUE THREAD

**Issue by ai** [ben-eb/cssnano#11]
For example, `rotation` is very popular keyframes and libraries and 3th part widgets often contains it.

/cc @ben-eb

**Comment by ben-eb** [comment]
Could you provide a code example?

**Comment by ai** [comment]
Input

```css
.mygalary_loader {
    animation: mygalary_rotation 1s linear infinite;
}

@keyframes mygalary_rotation {
    from {
        transform: rotate(0);
    }
    to {
        transform: rotate(360deg);
    }
}

.loader {
    animation: rotation 1s linear infinite;
}

@keyframes rotation {
    from {
        transform: rotate(0);
    }
    to {
        transform: rotate(360deg);
    }
}
```

Output:

```css
.mygalary_loader {
    animation: mygalary_rotation 1s linear infinite;
}

@keyframes mygalary_rotation {
    from {
        transform: rotate(0);
    }
    to {
        transform: rotate(360deg);
    }
}

.loader {
    animation: mygalary_rotation 1s linear infinite;
}
```
