### ISSUE TITLE
overflow-x and overflow-y properties overridden by combining of rules

### ISSUE THREAD

**Issue by dancoates** [ben-eb/cssnano#113]
Just ran into this issue. When given this input:

```css
.item {
    overflow: visible;
    overflow-x: hidden;
}

.item2 {
    overflow: visible;
}
```
cssnano will produce this output:
```css
.item{overflow-x:hidden}.item,.item2{overflow:auto}
```
Where the second rule overrides the first one and produces a different result to the unoptimized css.

**Comment by ben-eb** [comment]
My output is this, but it's a bug nonetheless:

```css
.item{overflow-x:hidden}.item,.item2{overflow:visible}
```

I'm fairly sure that this is a duplicate of https://github.com/ben-eb/postcss-merge-rules/issues/13, you may work around by disabling rule merging; `{mergeRules: false}`.
