### ISSUE TITLE
ConvertValues: Breaks SVG CSS Animation

### ISSUE THREAD

**Issue by swernerx** [ben-eb/cssnano#123]
The unit for `0%` is being stripped by cssnano. This works flawlessly in most browsers but not in IE (including Edge). This completely disables the animation in these browsers incl. the animation events and broke our whole application.

``` css
.amcharts g path{
  animation: css-effect 0.2s linear forwards;
}

@keyframes css-effect {
  0% {
    stroke-dashoffset: 200%;
  }

  50% {
    stroke-dashoffset: 100%;
  }

  100% {
    stroke-dashoffset: 0%;
  }
}
```

Current result of `cssnano --no-core test.css`:

``` css
.amcharts g path{
  animation:a .2s linear forwards;
}

@keyframes a{
  0%{
    stroke-dashoffset:200%;
  }

  50%{
    stroke-dashoffset:100%;
  }

  to{
    stroke-dashoffset:0;
  }
}
```

Expected result:

``` css
.amcharts g path{
  animation:a 0.2s linear forwards;
}

@keyframes a{
  0%{
    stroke-dashoffset:200%;
  }

  50%{
    stroke-dashoffset:100%;
  }

  to{
    stroke-dashoffset:0%;
  }
}
```

Maybe there has to be some more blacklisting of allowed non-unit properties.

**Comment by TrySound** [comment]
@swernerx As fast decision you can pass `convertValues: false` option.

**Comment by swernerx** [comment]
Thanks! That exactly what I did for now :) Works fine.

**Comment by ben-eb** [comment]
In your expected result, is the leading zero supposed to be there?

```css
.amcharts g path{
  animation:a 0.2s linear forwards;
}
```

Or can we still optimise that?

```css
.amcharts g path{
  animation:a .2s linear forwards;
}
```

**Comment by swernerx** [comment]
I figure it is not required. I think the main issue is actually the percent value in the animation step.

**Comment by ben-eb** [comment]
@swernerx OK. Is this a property-specific issue (just affects `stroke-dashoffset`), or can you reproduce with other properties? I don't have Windows so I can't test this out properly.

**Comment by swernerx** [comment]
I am not sure actually. We just need this/tested this with that property.

**Comment by cedriceberhardt** [comment]
It is an Edge-only bug (SVG animations aren't supported in >=IE11 and supported without units in other browsers). I am not entirely sure but it should affect everything that can be animated via CSS. So `stroke-dasharray` and `stroke-width`as well. I think only those can be animated via CSS?

If fact, you just need a unit, whatever it is. `%`, `px`, etc and only for what is animated. Which means that `stroke-dashoffset: 0` works if not animated via CSS. Like for an un-animated hover effect for instance.

CSS `transform` of SVG elements don't work on actual version of Edge.

**Comment by ben-eb** [comment]
OK, so for IE we shouldn't strip the unit in `@keyframes` rules?

**Comment by ben-eb** [comment]
Fixed in postcss-convert-values 2.3.5.

**Comment by jas-chen** [comment]
It still strip the unit in @keyframes rules (postcss-convert-values v2.6.1).

Source:
```css
@keyframes test {
  0% {
    background-position-x: 0%;
  }
  
  100% {
    background-position-x: 100%;
  }
}

body {
    animation-name: test;
}
```

Result:
```css
@keyframes a{0%{background-position-x:0}to{background-position-x:100%}}body{animation-name:a}
```

This behavior breaks animations in IE11. Please consider re-open this issue.
