### ISSUE TITLE
Error processing sketchy css background property

### ISSUE THREAD

**Issue by apexskier** [ben-eb/cssnano#129]
Given the css:

```css
.test {
  background: url('http://example.com/testing/test.png') no-repeat right #fff;
}
```

cssnano produces the error `TypeError: Cannot read property 'value' of undefined`

Depending on the build tool (gulp, postcss, cli) this is expressed in different ways, but here's an example script.

```js
var postcss = require('postcss');
var cssnano = require('cssnano');
var fs = require('fs');

postcss([cssnano()])
	.process(fs.readFileSync('example.css'), {
		from: 'example.css',
		to: 'example.min.css'
	}).then(function(result) {
		fs.writeFileSync('example.min.css', result.css);
	}).catch(function(err){
		console.warn(err);
	});
```

I realize this css isn't completely correct, but it should be dealt with, or a warning raised. Chrome actually parses it correctly, so that's why it wasn't caught before now, I think.
