### ISSUE TITLE
Should we remove all comments by default?

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/cssnano#132]
Currently we preserve 'important' comments (comments that start with `/*!`) by default, unless the `removeAll` option is set to `true`. This is because of license comments mostly, but I'm not sure if the behaviour is what people expect us to do by default.

Opinions on this are welcome, if we reach a consensus on changing this option then it will be done for version 4.

**Comment by sylvainpolletvillard** [comment]
The current behavior seems to be the most logical thing to do in my opinion.

**Comment by jonathantneal** [comment]
The current behavior follows expectations. I’d much prefer you keep it that way.

**Comment by andyjansson** [comment]
I have to agree with @sylvainpolletvillard and @jonathantneal, keep it as-is. It's the convention we've come to expect from using other tools.

**Comment by timaschew** [comment]
agree to keep the current behavior

**Comment by paxperscientiam** [comment]
After much head scratching, I discovered what appears to be a bug related to how cssnano preserves comments. Well, I'm not 100% sure, but I am sure that setting discardComments to true allowed the following style rules to be successfully applied:

```css
/**
 * Blackboard theme
 *
 * Adapted from Domenico Carbotta's TextMate theme of the same name
 *
 * @author Domenico Carbotta
 * @author Craig Campbell
 * @version 1.0.2
 */pre{background:#0b1022;word-wrap:break-word;margin:0;padding:0;padding:10px;color:#fff;font-size:14px;margin-bottom:20px}code,pre{font-family:Monaco,courier,monospace}pre .comment{color:#727272}pre .constant{color:#d8fa3c}pre .storage{color:#fbde2d}pre .comment.docstring,pre .string{color:#61ce3c}pre .string.regexp,pre .support.tag.script,pre .support.tag.style{color:#fff}pre .keyword,pre .selector{color:#fbde2d}pre .inherited-class{font-style:italic}pre .entity{color:#ff6400}[data-language=c] .function.call,pre .support{color:#8da6ce}pre .variable.class,pre .variable.global,pre .variable.instance{color:#ff6400}
```
This is output from cssnano applied to blackboard.css of the rainbowjs library. Preserving comments, as in the above example, blocked the style rules from being applied.
