### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dfcreative** [ben-eb/cssnano#14]
Hello!
Faced a bug.
A css chunk:
```css
@keyframes fadeOut{
	0%{
		opacity: 1;
	}
	100%{
		opacity: 0;
	}
}
@keyframes fadeOut {
	0% {
		opacity: 1;
	}
	100% {
		opacity: 0;
	}
}
.fadeOut{
    animation-name: fadeOut;
}
```

If to call `cssnano style.css style.min.css` it results in:

```
$ cssnano ../css/style.css ../css/style.min.css
/usr/local/lib/node_modules/cssnano/node_modules/postcss/lib/lazy-result.js:194
            throw error;
                  ^
RangeError: Maximum call stack size exceeded
    at recurse (/usr/local/lib/node_modules/cssnano/node_modules/postcss-merge-idents/index.js:7:29)
    at recurse (/usr/local/lib/node_modules/cssnano/node_modules/postcss-merge-idents/index.js:9:20)
    at recurse (/usr/local/lib/node_modules/cssnano/node_modules/postcss-merge-idents/index.js:9:20)
    at recurse (/usr/local/lib/node_modules/cssnano/node_modules/postcss-merge-idents/index.js:9:20)
    at recurse (/usr/local/lib/node_modules/cssnano/node_modules/postcss-merge-idents/index.js:9:20)
    at recurse (/usr/local/lib/node_modules/cssnano/node_modules/postcss-merge-idents/index.js:9:20)
    at recurse (/usr/local/lib/node_modules/cssnano/node_modules/postcss-merge-idents/index.js:9:20)
    at recurse (/usr/local/lib/node_modules/cssnano/node_modules/postcss-merge-idents/index.js:9:20)
    at recurse (/usr/local/lib/node_modules/cssnano/node_modules/postcss-merge-idents/index.js:9:20)
    at recurse (/usr/local/lib/node_modules/cssnano/node_modules/postcss-merge-idents/index.js:9:20)
```
