### ISSUE TITLE
Feature request: remove spaces from calc()

### ISSUE THREAD

**Issue by dikmax** [ben-eb/cssnano#142]
Right now content of `calc()` function is can only be optimized if there's same units. If units differs then content is left intact, but spaces can be safely removed.

```css
.a {
    font-size:calc(14px + 6 * ((100vw - 320px) / 448)); 
}
```

can be optimized to this

```css
.a{font-size:calc(14px+6*((100vw-320px)/448))}
```
