### ISSUE TITLE
cssnano changes values after minification

### ISSUE THREAD

**Issue by necramirez** [ben-eb/cssnano#143]
I have this in my gulpfile:
```js
var gulp = require('gulp');
var concat = require('gulp-concat');
var cssnano = require('gulp-cssnano');

var vendorCssFiles = [
  'node_modules/angular-material/angular-material.css'
];

gulp.task('vendor-css', function () {
  return gulp.src(vendorCssFiles)
    .pipe(cssnano())
    .pipe(concat('vendor.css'))
    .pipe(gulp.dest('./public/css'));
});
```

The source CSS file has this:
```css
.md-open-menu-container {
  position: fixed;
  left: 0;
  top: 0;
  z-index: 100;
  opacity: 0;
  border-radius: 2px; }
```

The resulting `vendor.css` has this instead:
```css
.md-open-menu-container{position:fixed;left:0;top:0;z-index:19;opacity:0;border-radius:2px}
```

The `z-index` value changes from `100` to `19`. How come?
