### ISSUE TITLE
transition broken

### ISSUE THREAD

**Issue by stevenvachon** [ben-eb/cssnano#150]
before:
```css
rule {
  transition: prop1 1s, prop2 0s 1s;  /* 0s duration after a 1s delay */
}
```
after:
```css
rule {
  transition: prop1 1s;
}
```
