### ISSUE TITLE
Handling different @keyframes rules with the same identifier

### ISSUE THREAD

**Issue by Justineo** [ben-eb/cssnano#171]
Input:

```css
.box {
  animation-name: spin;
}

@keyframes spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}

/* different angle */
@keyframes spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(720deg);
  }
}

/* different order */
@keyframes spin {
  100% {
    transform: rotate(360deg);
  }
  0% {
    transform: rotate(0deg);
  }
}

/* different unit */
@keyframes spin {
  0% {
    transform: rotate(0turn);
  }
  100% {
    transform: rotate(2turn);
  }
}
```

All `@keyframes` are preserved after minification now but in fact only the last one is valid. Currently only `@keyframes` with exactly same style rules and identifier can be handled correctly.
