### ISSUE TITLE
Sorting rule sets according to selector specificity

### ISSUE THREAD

**Issue by Justineo** [ben-eb/cssnano#172]
Input:

``` css
.title {
  color: #69c;
}

.post .title {
  font-weight: 700;
}

.title {
  line-height: 2;
}
```

Currently all rule sets are preserved after minification. Actually we can **safely** transform this into:

``` css
.title {
  color: #69c;
}

.title {
  line-height: 2;
}

.post .title {
  font-weight: 700;
}
```

And the first two rule sets can be merged into one, utilizing current optimization for adjacent rules:

``` css
.title {
  color: #69c;
  line-height: 2;
}

.post .title {
  font-weight: 700;
}
```

**Comment by ben-eb** [comment]
PR still welcome for this. 👍

https://github.com/ben-eb/postcss-merge-rules/issues/7

**Comment by Justineo** [comment]
The problem is not that simple on a second thought :(

If we have a style rule with grouped selectors, sorting become quite complicated:

```css
.post {
  font-size: 1.5rem;
}

#title, a {
  color: #ccc;
}

.post {
  color: #69c;
}
```

In this case rules with `.post` selector cannot be safely merged because `#title, a` has both a higher and lower specificity than `.post`.
