### ISSUE TITLE
Unexpected results with autoprefixer, precss and cssnano

### ISSUE THREAD

**Issue by chrisberthe** [ben-eb/cssnano#174]
I'm having an issue with combining `autoprefixer`, `precss` and `cssnano`. Consider the following code:
```scss
@for $i from 1 to 3 {
  .b-$i { display: flex; width: $(i)px; }
}
```
Compiles to:
```css
.b-1{width:1px}
.b-1,.b-2{display:-webkit-flex;display:-ms-flexbox;display:flex}
.b-2{width:2px}
.b-3{display:-webkit-flex;display:-ms-flexbox;display:flex;width:3px}
```
Expected result:
```css
.b-1{width:1px}
.b-2{width:2px}
.b-3{width:3px}
.b-1,.b-2,.b-3{display:-webkit-flex;display:-ms-flexbox;display:flex}
```

You can replicate this by creating a `dist` folder and `styles.scss`, copying the code above and  executing the following command:
```bash
postcss styles.scss -u autoprefixer -u precss -u cssnano -d dist
```
