### ISSUE TITLE
-webkit-flex-wrap being stripped

### ISSUE THREAD

**Issue by twhid** [ben-eb/cssnano#195]
Greetings!

Inherited an issue from a vacationing dev. Hoping to find some help here.

We're having a prefix being stripped that is required for Safari 8. We believe we've tracked it down to cssnano (invoked via webpack). 

Here are my test results.

Given this input as test.css:
```css
.selector {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-flex-wrap: wrap;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
}
```

Running..
```
$ cssnano -v
cssnano v3.6.2 (cli v1.0.4)
$ cssnano ./test.css test.min.css
```
This is the result (linebreaks added for clarity):
```css
.selector {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap
}
```
As you can see, the `-webkit-flex-wrap` rule is stripped.

Given this input:
```css
.selector {
    -webkit-flex-wrap: wrap;
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
}
```
This is the result:
```css
.selector {
    -webkit-flex-wrap: wrap;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap
}
```

The `-webkit-flex-wrap` is left intact.

Am I barking up the wrong tree? Perhaps autoprefixer is the issue?

Thanks for any help.
