### ISSUE TITLE
border: none was broke by "0 0" value

### ISSUE THREAD

**Issue by ai** [ben-eb/cssnano#20]
I have

```css
button {
  border: none;
}
```

cssnano coverts it to:

```css
button{border:0 0}
```

but `0 0` is wrong value, `0` is correct.

@ben-eb Seems like it is not [postcss-convert-values](https://github.com/ben-eb/postcss-convert-values) issue, so I report it here.
