### ISSUE TITLE
Remove overridden rules

### ISSUE THREAD

**Issue by andrey-hohlov** [ben-eb/cssnano#200]
Hi! 
Is there way to remove overridden rules like [csso](https://github.com/css/csso)?

For examle
```css
.btn {
  border: none;
  border: 1px solid red;
}
```
turn in:
```css
.btn {
  border: 1px solid red;
}
```
