### ISSUE TITLE
Order of properties causes unwanted overwrite

### ISSUE THREAD

**Issue by ramono** [ben-eb/cssnano#201]
The following block of code
```
.head {
    position: relative;
    &::before {
        content: "";
        position: absolute;
        display: block;
        bottom: 0;
        left: 0;
        width: 50%;
        border-left: 0;
        box-sizing: border-box;
        border-style: solid;
        border-color: transparent;
        border-bottom-color: blue;
    }
    &::after {
        content: "";
        position: absolute;
        display: block;
        bottom: 0;
        right: 0;
        width: 50%;
        border-right: 0;
        box-sizing: border-box;
        border-style: solid;
        border-color: transparent;
        border-bottom-color: blue;
    }
}
```
Is compiled with a different order when parsed with cssnano, causing a visual difference in the browser, the following is the non-compressed output:
```
.head {
  position: relative; }
  .head::before {
    content: "";
    position: absolute;
    display: block;
    bottom: 0;
    left: 0;
    width: 50%;
    border-left: 0;
    box-sizing: border-box;
    border-style: solid;
    border-color: transparent;
    border-bottom-color: blue; }
  .head::after {
    content: "";
    position: absolute;
    display: block;
    bottom: 0;
    right: 0;
    width: 50%;
    border-right: 0;
    box-sizing: border-box;
    border-style: solid;
    border-color: transparent;
    border-bottom-color: blue; }
```
And the following is the code output after cssnano:

```
.head {
	position:relative;
}
.head:before {
	left:0;
	border-left:0;
	border-bottom-color:blue; /* this rule */
}
.head:after,.head:before {
	content:"";
	position:absolute;
	display:block;
	bottom:0;
	width:50%;
	box-sizing:border-box;
	border-color:transparent; /* is overwritten here */
	border-style:solid;
}
.head:after {
	right:0;
	border-right:0;
	border-bottom-color:blue;
}
```
As a result, `.head:before` has a transparent `border-bottom` color because this property is being overwritten by the next set of selectors.

I understand there are better ways to write this code, which I did, but I believe this should not happen in any case. I'm I wrong and is this supposed to happen?

Thanks.

**Comment by ben-eb** [comment]
It's probably a bug with postcss-merge-rules. 😄

However I get a different output;

```css
.head {
    position:relative;
}

.head:before {
    left:0;
    border-left:0;
}

.head:after,.head:before{
    content:"";
    position:absolute;
    display:block;
    bottom:0;
    width:50%;
    box-sizing:border-box;
    border-style:solid;
    border-color:transparent;
    border-bottom-color:blue;
}

.head:after {
    right:0;
    border-right:0;
}
```

Are you using the latest version?
