### ISSUE TITLE
IE8 issue

### ISSUE THREAD

**Issue by VodkaBears** [ben-eb/cssnano#21]
Hi!

After processing `background: url(image.png) no-repeat` becomes `background:url(image.png)no-repeat`. As you see, there is no whitespace character between properties, so it causes IE8 to fail parsing.

**Comment by ben-eb** [comment]
Hello :smile:

I've seen this sort of behaviour work in Chrome; if you have a CSS rule like this:

```css
h1 {
  border-color: rgb(255,255,255) rgb(200,200,200) rgb(150,150,150) rgb(100,100,100);
}
```

It can be compressed to:

```css
h1 {
  border-color: rgb(255,255,255)rgb(200,200,200)rgb(150,150,150)rgb(100,100,100);
}
```

Does this fail in IE8 too? Should I remove this behaviour?
