### ISSUE TITLE
Calc statements no longer being reduced

### ISSUE THREAD

**Issue by Dylan-Chapman** [ben-eb/cssnano#211]
I'm using Lost grid on my site. Occasionally it will spit out a rule like

``` css
.element {
    width: calc(99.99% * 1/1 - 0rem);
}
```

Previously, this would be reduced to `width: 99.99%;`, however, now it is left as-is. Anyway to resolve this? Was this change intentional?
