### ISSUE TITLE
Background none replacement with 0 0

### ISSUE THREAD

**Issue by thomasjbradley** [ben-eb/cssnano#23]
I’m having trouble with these lines in the core.js file:
https://github.com/ben-eb/cssnano/blob/master/lib/core.js#L27-L29

```js
if (declaration.prop === 'background') {
  declaration.value = declaration.value.replace('none', '0 0');
}
```

The code doesn’t work for me if I specify `none` as a background image, because replacing it with 0 0 wrecks the whole declaration.

With CSS like this:

```css
h1 {
    background: none left top / cover no-repeat transparent;
}
```

I would expect this result:

```css
h1{background:none left top/cover no-repeat transparent}
```

But instead the `none` gets replaced with `0 0` mucking up the image value and the browser interprets it as a position or something.

```css
h1{background:0 0 left top/cover no-repeat transparent}
```

Any thoughts on what I can do about it?

**Comment by ben-eb** [comment]
What is the purpose of this rule?

```css
h1 {
    background: none left top / cover no-repeat transparent;
}
```

If you think that the `none` is better left untouched I can remove that logic.

**Comment by thomasjbradley** [comment]
I would use that rule for something like icons.
To do the basic set up, I could target all the icon classes like this:

```css
.icon {
  background: none left top / cover no-repeat transparent;
  width: 32px;
  height: 32px;
  ...
}
```

Then for each unique icon, I only have to specify the image:

```css
.icon-github {
  background-image: url(...);
}
```
