### ISSUE TITLE
Flexbox 2012 and 2009 syntaxes

### ISSUE THREAD

**Issue by zellwk** [ben-eb/cssnano#231]
When minifiying, cssnano changes Flexbox's 2012 syntax into the 2009 syntax for webkit. 

The original code:
```
.selector {
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
}
```

Minified code:
```
.selector {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
}
```
It breaks most browsers that only support the 2012 syntax. Is this deliberate or a bug?

**Comment by ben-eb** [comment]
With the latest version (cssnano v3.7.3 (cli v1.0.4)), no webkit fallback is provided;

```css
.selector{display:-ms-flexbox;display:flex}
```

If I enable all browsers instead (`cssnano --autoprefixer.browsers '>0%'`);

```css
.selector{display:-webkit-flex;display:-ms-flexbox;display:flex}
```

My guess is that you are using an old version?
