### ISSUE TITLE
outline: none VS outline: 0

### ISSUE THREAD

**Issue by Olivia101** [ben-eb/cssnano#234]
Again when I tried to minifiy Bootstrap v4 files using cssnano 3.7.3 I noticed that outline:0 was converted to outline:none
Apparently there is a difference between the two: http://stackoverflow.com/questions/35648667/outline-none-vs-outline-0

**Comment by ben-eb** [comment]
We don't transform those values *because* of the difference; do you have something that reproduces this? I just tried with the CLI now;

```css
h1 {
  outline: 0;
}

/* becomes */
h1{outline:0}
```

and;

```css
h1 {
  outline: none;
}

/* becomes */
h1{outline:none}
```
