### ISSUE TITLE
border:none -> border:0

### ISSUE THREAD

**Issue by stevenvachon** [ben-eb/cssnano#238]
```js
require("cssnano").process("a { border: none }").then(result => console.log(result.css))
```
produces:
```css
a{border:none}
```
However, it'd be smaller if it produced:
```css
a{border:0}
```
