### ISSUE TITLE
mergeldents documentation error

### ISSUE THREAD

**Issue by stevenvachon** [ben-eb/cssnano#259]
the "before" should be:
```css
.box {
  animation-name: dissolve;
}
```
http://cssnano.co/optimisations/#mergeidents

I couldn't find the file to edit for a PR, so I created this instead.
