### ISSUE TITLE
Feature: Convert ellipsis to … (text-overflow)

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/cssnano#266]
Input:

```css
h1 {
  text-overflow: ellipsis;
}

Output:

```css
h1 {
  text-overflow: '…';
}
```

Slightly shorter but no good browser support (yet).
