### ISSUE TITLE
Feature: Convert doubled border-spacing values.

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/cssnano#267]
The second argument to this can be removed if it is the same.

``` css
h1 {
  border-spacing: 10px 10px;
}
```

Output:

``` css
h1 {
  border-spacing: 10px;
}
```
