### ISSUE TITLE
Issue: border-color merge

### ISSUE THREAD

**Issue by novajohn** [ben-eb/cssnano#280]
I have a piece of style like this:

```css
.target {
  border-right-color: #000;
  border-top-color: #000;
  border-left-color: #000;
  border-bottom-color: #000;
}
```

**cssnano**  will transform it into:

```css
.target {
  border: #000;
}
```

but the correct output should be:

```css
.target {
  border-color: #000;
}
```

Colors should be merged to **border-color** and not just to **border** style.
