### ISSUE TITLE
Reduce Aspect Ratio Fraction

### ISSUE THREAD

**Issue by tomhodgins** [ben-eb/cssnano#318]
```css
@media (min-aspect-ratio: 160000000000/90000000000) {
  :root {
    background: lime;
  }
}
```

## correct minification

```css
@media (min-aspect-ratio:16/9){:root{background:lime}}
```

- ratio value can be reduced

## CSSnano output

```css
@media (min-aspect-ratio:160000000000/90000000000){:root{background:lime}}
```

- ratio numbers keep unneeded `0000000000`

**Comment by ben-eb** [comment]
Sounds good to me, note that we can also simplify fractions - `32/18` can be `16/9` instead, as per the specification: https://www.w3.org/TR/css3-mediaqueries/#device-aspect-ratio

**Comment by ben-eb** [comment]
Fixed in https://github.com/ben-eb/postcss-minify-params/commit/61aa01bb231594cc3f067ef874e0d5d4acf0eb8f.

**Comment by strarsis** [comment]
@ben-eb: This feature is nice! Though it doesn't work with the usual `aspect-ratio` property.

```css
.test {
  aspect-ratio: 160000000000/90000000000;
}
````
Is there a rational for not doing the same simplification with values of the `aspect-ratio` property?
