### ISSUE TITLE
calc() optimization

### ISSUE THREAD

**Issue by tomhodgins** [ben-eb/cssnano#320]
```css
div {
  background : lime ;
  width : calc(50% + (5em + 5%)) ;
  height : calc(50% + (5em + 5%)) ;
}
```

## correct minification

```css
div{background:lime;width:calc(55% + 5em);height:calc(55% + 5em)}
```

- even without evaluating it, the formula can be consolidated further

## CSSnano output

```css
div{background:lime;width:calc(50% + (5em + 5%));height:calc(50% + (5em + 5%))}
```

- the `50%` and `5%` can be added together
