### ISSUE TITLE
in case of insensitivity

### ISSUE THREAD

**Issue by tomhodgins** [ben-eb/cssnano#321]
```css
.test {
  background: red;
}
.TEST {
  color: blue;
}
```

## correct minification

```css
.test{background:red;color:blue}
```

- class names (and many other things) are not case sensitive in CSS

## CSSnano output

```css
.test{background:red}.TEST{color:blue}
```

- `.test`, `.TEST` and any combination of lowercase and uppercase letters in class selectors are equivalent
