### ISSUE TITLE
media query extra space

### ISSUE THREAD

**Issue by tomhodgins** [ben-eb/cssnano#324]
```css
@media (min-width: 1px) {
  :root {
    background: lime;
  }
}
```

## correct minification

```css
@media(min-width:1px){:root{background:lime}}
```

- whitespace not required after `@media` unless followd by a word like `screen`, etc.

## CSSnano output

```css
@media (min-width:1px){:root{background:lime}}
```

- left optional whitespace after `@media`
