### ISSUE TITLE
property stacking

### ISSUE THREAD

**Issue by tomhodgins** [ben-eb/cssnano#326]
This one really surprised me - it did it with `color`, `background`, lots of things!

```css
html {
  background: red;
}
html {
  background: orange;
}
html {
  background: yellow;
}
html {
  background: green;
}
html {
  background: blue;
}
html {
  background: indigo;
}
html {
  background: violet;
}
```

## correct minification

```css
html{background:violet}
```

- redundant properties can be eliminated

## CSSnano output

```css
html{background:red;background:orange;background:#ff0;background:green;background:blue;background:indigo;background:violet}
```

- keeps previously declared `background` properties even though it can predict they won't apply
