### ISSUE TITLE
remove zero units

### ISSUE THREAD

**Issue by tomhodgins** [ben-eb/cssnano#327]
```css
.remove-zero-unit {
  max-height: 0%;
  height: 0%;
  font-size: calc(0%);
  transform: rotateZ(0deg);
}
```

## correct minification

```css
.remove-zero-unit{max-height:0;height:0;font-size:0;transform:rotateZ(0)}
```

- removes `%` and `deg` units where they can be safely eliminated

## CSSnano output

```css
.remove-zero-unit{max-height:0%;height:0%;font-size:0%;transform:rotate(0deg)}
```

- should it be `rotateZ(0)` instead of `rotate()`? what if another rule has `roatateY()` set?
- can remove unit from % on `height` and `max-height` properties
- can remove `deg` from `0deg`
- can remove `%` if final simplification from calc is `0%`

**Comment by ben-eb** [comment]
* `rotateZ(0)` is invalid, as a unitless zero is a `<length>` value and not an `<angle>` value. https://developer.mozilla.org/en-US/docs/Web/CSS/angle
* `max-height` & `height` behave differently with a `%`, see https://github.com/ben-eb/css-minifier-tests/tree/master/tests/111-keepZeroPercentHeight
* `calc` might be correct, will have to investigate this further.

**Comment by ben-eb** [comment]
`calc` is complex, it depends on the property and the DOM. `0` is considered as a `<length>` value and not a `<percentage>` value, so by removing the `%` you are actually changing the type of the value. 

For more information, see: https://github.com/ben-eb/cssnano/issues/229

**Comment by davidhund** [comment]
Hi @ben-eb — I think I just stumbled on a related issue.

I removed `postcss-calc` as a postcss-cli plugin because I'm [already using cssnano](https://twitter.com/cssnano_/status/819210493869117440)

Given the following CSS… 

```css
:root { --wi-gutter: 1rem; };
.test { margin: calc(-.5 * var(--wi-gutter)); }
```
…I noticed cssnano keeps leading zero's. I *think* they are safe to remove?

**With `postcss-calc@5.3.1`:**

```css
.test{margin:-.5rem}
```

**With `cssnano@3.10.0` (`postcss-calc@5.2.0`):**

```css
.test{margin:-0.5rem}
```

Is this expected behaviour or a postcss-calc or cssnano issue?
