### ISSUE TITLE
output wrong value for z-index 

### ISSUE THREAD

**Issue by song940** [ben-eb/cssnano#330]
i found this http://cssnano.co/optimisations/zindex, but i am not understand

> it is safe if your stacking context has wholly been extracted into CSS.

before
a.css
```css
.overlay{
  z-index: 999;
}
```
b.css
```css
@import 'a';

.modal{
  z-index: 998;
}
```

after
```css
.overlay{
  z-index: 1;
}
.modal{
  z-index: 1;
}
```

FYI: cssnano@3.9.1
