### ISSUE TITLE
Add CSS multiple animation syntax support

### ISSUE THREAD

**Issue by DeathMiner** [ben-eb/cssnano#34]
Hello,

When using multiple animations in the same ``animation`` property, the first one works, but the second one gets its keyframes deleted.

Code used:
```css

@keyframes three-quarters-loader {
	0% {
	  transform: rotate(0deg);
	}
	100% {
	  transform: rotate(360deg);
	}
}

@keyframes loaderIn{
	from{
		border-width:0;
		opacity:0;
	}
}

.loader {
	animation: three-quarters-loader 1250ms infinite linear, loaderIn .3s ease-out both; /* Only the first animation plays */
}
```

Cheers!

**Comment by ben-eb** [comment]
Is the above your input CSS, or the result of the transform?

**Comment by DeathMiner** [comment]
Sorry i forgot to mention that it was the input code.

**Comment by ben-eb** [comment]
* Rebasing keyframes was fixed in https://github.com/ben-eb/postcss-reduce-idents/commit/99fba2956002585de03f997e628c8cdbe094dd14
* Unused logic was fixed in https://github.com/ben-eb/postcss-discard-unused/commit/04be6cfc88575ece37fbd8237dafcc87c3191d6c

Resulting CSS:

```css
@keyframes a{0%{transform:rotate(0deg)}to{transform:rotate(360deg)}}@keyframes b{0%{border-width:0;opacity:0}}.loader{animation:a 1.25s infinite linear,b .3s ease-out both}
```
