### ISSUE TITLE
Keep the IE9 hack

### ISSUE THREAD

**Issue by yibuyisheng** [ben-eb/cssnano#342]
Suppose there is the following css code:

```css
.selector {
  top: 15px;
  top: 0\9\0; /* hack for IE9 */
}
```

After being Compiled with cssnano, the output is:

```css
.selector {
  top: 15px;
  top: 0; /* hack for IE9 */
}
```

The `\9\0` disappears!!

But when the `hack top` property dose not start with `0`, the output is correct:

```css
.selector {
  top: 15px;
  top: 0.5px\9\0; /* hack for IE9 */
}
```

The output is:

```css
.selector {
  top: 15px;
  top: .5px\9\0; /* hack for IE9 */
}
```
