### ISSUE TITLE
Remove redundant :not()'s

### ISSUE THREAD

**Issue by stevenvachon** [ben-eb/cssnano#345]
```css
element:not(.classA):not(.classA):not(.classB) {
  color: green;
}
```
should produce:
```css
element:not(.classA):not(.classB) {
  color: green;
}
```
