### ISSUE TITLE
cssnano doesn't strip duplicate padding

### ISSUE THREAD

**Issue by yivo** [ben-eb/cssnano#350]
**Input:**
```css
.btn {
    padding: 0;
    padding: 3px 6px;
}
```

**Output:**
```css
.btn{padding:0;padding:3px 6px}
```

**Expected output:**
```css
.btn{padding:3px 6px}
```

**cssnano version:**
```
cssnano v3.10.0 (cli v1.0.5)
```
