### ISSUE TITLE
Strange rule optimisations

### ISSUE THREAD

**Issue by remitbri** [ben-eb/cssnano#36]
I'm using cssnano 2.0.3 as required (`"cssnano": "^2.0.1"`) by cssnext 1.8.0.

From a bunch of rules, cssnano out of the box takes identical proprieties/values from more or less adjacent classnames (say `a{} b{}`) and creates a new rule `a,b{}` with the common proprieties/values. Is it possible to disable that? It can lead to nasty side effects. 

Moreover, depending on the classnames, the identical rules picked up for factorisation are not always the same!
Eg, from
```css
.foo {
  font-size: 13px;
  font-size: 0.8125rem;
  display: block;
  font-family: Trade Gothic, Trade Gothic W01, Trade Gothic wf, Helvetica Neue, Helvetica, Arial, sans-serif;
  font-weight: bold;
}

.bar {
  display: block;
  font-size: 11px;
  font-size: 0.6875rem;
}

.baz {
  font-size: 15px;
  font-size: 0rem;
  display: inline-block;
  border: 1px solid #fff;
  padding: 8px 10px;
  padding: 0.5rem 0.625rem;
  line-height: 1;
  font-family: Trade Gothic, Trade Gothic W01, Trade Gothic wf, Helvetica Neue, Helvetica, Arial, sans-serif;
  font-weight: bold;
}

.lorem,
.ipsum {
  font-size: 11px;
  font-size: 0.6875rem;
  display: block;
}
```

I get (if I make it readable)

```css
.foo {
  font-size: 13px;
  font-size: .8125rem;
  font-family: Trade Gothic, Trade Gothic W01, Trade Gothic wf, Helvetica Neue, Helvetica, Arial, sans-serif;
  font-weight: 700
}

.bar,
.foo {
  display: block
}

.bar {
  font-size: 11px;
  font-size: .6875rem
}

.baz {
  font-size: 15px;
  font-size: 0;
  display: inline-block;
  border: 1px solid #fff;
  padding: 8px 10px;
  padding: .5rem .625rem;
  line-height: 1;
  font-family: Trade Gothic, Trade Gothic W01, Trade Gothic wf, Helvetica Neue, Helvetica, Arial, sans-serif;
  font-weight: 700
}

.ipsum,
.lorem {
  font-size: 11px;
  font-size: .6875rem;
  display: block
}
```

In this case, it's `display: block` from `.bar` and `.foo`.
But here : 

```css
.foobam {
  font-size: 13px;
  font-size: 0.8125rem;
  display: block;
  font-family: Trade Gothic, Trade Gothic W01, Trade Gothic wf, Helvetica Neue, Helvetica, Arial, sans-serif;
  font-weight: bold;
}

.barem {
  display: block;
  font-size: 11px;
  font-size: 0.6875rem;
}

.bazzaz {
  font-size: 15px;
  font-size: 0rem;
  display: inline-block;
  border: 1px solid #fff;
  padding: 8px 10px;
  padding: 0.5rem 0.625rem;
  line-height: 1;
  font-family: Trade Gothic, Trade Gothic W01, Trade Gothic wf, Helvetica Neue, Helvetica, Arial, sans-serif;
  font-weight: bold;
}

.loremL,
.ipsumI {
  font-size: 11px;
  font-size: 0.6875rem;
  display: block;
}
```
(i.e, same as the first example, except that the classnames have changed)

I get

```css
.foobam {
  font-size: 13px;
  font-size: .8125rem;
  display: block
}

.barem {
  display: block;
  font-size: 11px;
  font-size: .6875rem
}

.bazzaz,
.foobam {
  font-family: Trade Gothic, Trade Gothic W01, Trade Gothic wf, Helvetica Neue, Helvetica, Arial, sans-serif;
  font-weight: 700
}

.bazzaz {
  font-size: 15px;
  font-size: 0;
  display: inline-block;
  border: 1px solid #fff;
  padding: 8px 10px;
  padding: .5rem .625rem;
  line-height: 1
}

.ipsumI,
.loremL {
  font-size: 11px;
  font-size: .6875rem;
  display: block
}
```

Now the targeted classes are `.bazzaz` and `.foobam` with a proprieties `font-family` and `font-weight`!

**Comment by ben-eb** [comment]
Yep, it's possible to disable it, if you set `merge` to `false in your config:

```js
{
  compress: {merge: false}
}
```

The module should only compress adjacent rules so I'm not sure what happened here! I'll look into it.

**Comment by remitbri** [comment]
`merge`: thanks, Ben. I misread the actual explanations from the documentations and understood from the example it was only about adjacent classes.

I tried to explore and simplify a bit more, and still the weird thing.

---

**Case 1**
From
```css
.foo {
  margin: 0;
  display: block;
}

.barim {
  display: block;
  line-height: 1;
}

.bazaz {
  font-size: 3em;
  margin: 0;
}
```

I get
```css
.foo {
  margin: 0
}

.barim,
.foo {
  display: block
}

.barim {
  line-height: 1
}

.bazaz {
  font-size: 3em;
  margin: 0
}
```

=> Everything's as expected from `merge`.

---

**Case 2**
Same as Case 1, except… `.foo` becomes `.foobam`. No other change.
From

```css
.foobam {
  margin: 0;
  display: block;
}

.barim {
  display: block;
  line-height: 1;
}

.bazaz {
  font-size: 3em;
  margin: 0;
}
```

I get

```css
.foobam {
  margin: 0;
  display: block
}

.barim {
  display: block;
  line-height: 1
}

.bazaz {
  font-size: 3em;
  margin: 0
}
```

=> `.foobam` and `.barim` should have had a common rule

---

**Case 3**
Same as Case 1, except I replaced `margin: 0` with `font-family: serif`.
So, from

```css
.foobam {
  font-family: serif;
  display: block;
}

.barim {
  display: block;
  line-height: 1;
}

.bazaz {
  font-size: 3em;
  font-family: serif;
}
```

I get

```css
.foobam {
  display: block
}

.barim {
  display: block;
  line-height: 1
}

.bazaz,
.foobam {
  font-family: serif
}

.bazaz {
  font-size: 3em
}
```

=> our weird bug strikes again.
