### ISSUE TITLE
Keyframes name change

### ISSUE THREAD

**Issue by glennphilp** [ben-eb/cssnano#361]
Is there a way to turn-off name changing of @keyframes?

When I am running my files through CSSNano for production there are conflicts created with the outcome for keyframes.

fileone.scss
* _responsive-tabs.scss
```css
.tabs > .tab-content.active {
    animation: cd-fade-in 0.5s;
}

@keyframes cd-fade-in {
   0% { opacity: 0; }
   100% { opacity: 1; }
}
```
Output:
```css
.tabs>.tab-content.active{ animation: a 0.5s }
@keyframes a { 0%{opacity:0}to{opacity:1} }
```

filetwo.scss
* _slider.scss
```css
.slider > .slide { 
    animation: cd-shake 0.4s;
}

@keyframes cd-shake {
  ...
}
```

Output:
```css
.slider>.slide { animation: a 0.4s }
@keyframes a { ... }
```
When both fileone.css and filetwo.css are called on a page the tabs component ends up using the slider animation because of the name change conflict.
