### ISSUE TITLE
MergeLonghand rule with Properties being overwritten

### ISSUE THREAD

**Issue by PlaneTw** [ben-eb/cssnano#366]
the input is:
``` css
select {
  padding-bottom: calc(0.375em - 1px);
  padding-left: calc(0.625em - 1px);
  padding-right: calc(0.625em - 1px);
  padding-top: calc(0.375em - 1px);
  padding-right: 2.5em;
}
```

the output is:
``` css
select{padding:calc(.375em - 1px) 2.5em calc(.375em - 1px) calc(.625em - 1px);padding-right:calc(.625em - 1px)}
```

As a result, the result of output has wrong `padding-right`.
