### ISSUE TITLE
cssnano breaks font inclusions

### ISSUE THREAD

**Issue by OZZlE** [ben-eb/cssnano#37]
We are using this approach to include fonts in our css but this module seems to break it:

@import url("http://fast.fonts.net/t/1.css?apiType=css&projectid=[censor]");
@font-face{
    font-family: "avenir next light";
        src:url("../fonts/avenir/7bf72cf4ff-a744-4420-ad96-b982fd3cs23a7.eot?#iefix");
        src:url("../fonts/avenir/7bf72c4f-a74g4-4420-gad96-b982fd3cs23a7.eot?#iefix") format("eot"),
        url("../fonts/avenir/fd1f3434-eb5b-47f67-8593-e6cfcbfd15s58.woff2") format("woff2"),
        url("../fonts/avenir/f6ebea36-fb7c-4458-a43e-2f112c48c17e4.woff") format("woff"),
        url("../fonts/avenir/2d80c4f84e-3493-4ca8-ad53-b7decaf9a4f9.ttf") format("truetype"),
        url("../fonts/avenir/4869d6f6c-eff9f-49fc-9c1e-f3a65852fb092.svg#48696f6c-ef9f-49fc-9c1e-f3a65852b092") format("svg");
}

**Comment by ben-eb** [comment]
The defaults strip out "unused" declarations; i.e. it is looking for a rule that loads that font family. You can disable it with the `unused` option. On the CLI it looks like this:

```css
$ cssnano --no-unused
```

Output:

```css
@import url("http://fast.fonts.net/t/1.css?apiType=css&projectid=[censor]");@font-face{font-family:avenir next light;src:url(../fonts/avenir/7bf72cf4ff-a744-4420-ad96-b982fd3cs23a7.eot?#iefix);src:url(../fonts/avenir/7bf72c4f-a74g4-4420-gad96-b982fd3cs23a7.eot?#iefix) format("eot"),url(../fonts/avenir/fd1f3434-eb5b-47f67-8593-e6cfcbfd15s58.woff2) format("woff2"),url(../fonts/avenir/f6ebea36-fb7c-4458-a43e-2f112c48c17e4.woff) format("woff"),url(../fonts/avenir/2d80c4f84e-3493-4ca8-ad53-b7decaf9a4f9.ttf) format("truetype"),url(../fonts/avenir/4869d6f6c-eff9f-49fc-9c1e-f3a65852fb092.svg#48696f6c-ef9f-49fc-9c1e-f3a65852b092) format("svg")}
```
