### ISSUE TITLE
navbar's z-index changed from 3 to 4, resulting in navbar being hidden beneath toolbar at z-index 3

### ISSUE THREAD

**Issue by r3wt** [ben-eb/cssnano#372]
**input:**
```css
.navbar-wrapper-vr{
	position: fixed;
	top: 0;
	left: 0;
	right: 0;
	height: 64px;
	z-index: 4;
}
```
**output:**
```css
.navbar-wrapper-vr{
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    height: 64px;
    z-index: 3;
}
```
