### ISSUE TITLE
bug - postcss-minify-gradients

### ISSUE THREAD

**Issue by pigcan** [ben-eb/cssnano#386]
I found there is a bug during using css-nano - postcss-minify-gradients to process css `gradient `.

Here is my less file.

```less
@ratio:1/200;
@lightFrom: -10%;
@lightTo: 110%;
@section: (@lightTo - @lightFrom)/20;
@lightColor:rgba(178, 238, 121, 0.62);
@lightColor: #fff;
@lightRadius:40%;
@lightSize: 1;
@lightScale: 2.6;
@keyframes flash-anim{
  0%{
    background: -webkit-radial-gradient(50% 0*@section+@lightFrom, circle, @lightColor, rgba(255, 255, 255, 0) @lightRadius*.0);
  }
  5%{
    background: -webkit-radial-gradient(50% 1*@section+@lightFrom, circle, @lightColor, rgba(255, 255, 255, 0) @lightRadius*.1);
  }
  10%{
    background: -webkit-radial-gradient(50% 2*@section+@lightFrom, circle, @lightColor, rgba(255, 255, 255, 0) @lightRadius*.2);
  }
  15%{
    background: -webkit-radial-gradient(50% 3*@section+@lightFrom, circle, @lightColor, rgba(255, 255, 255, 0) @lightRadius*.3);
  }
  20%{
    background: -webkit-radial-gradient(50% 4*@section+@lightFrom, circle, @lightColor, rgba(255, 255, 255, 0) @lightRadius*.4);
  }
  25%{
    background: -webkit-radial-gradient(50% 5*@section+@lightFrom, circle, @lightColor, rgba(255, 255, 255, 0) @lightRadius*.5);
  }
  30%{
    background: -webkit-radial-gradient(50% 6*@section+@lightFrom, circle, @lightColor, rgba(255, 255, 255, 0) @lightRadius*.6);
  }
  35%{
    background: -webkit-radial-gradient(50% 7*@section+@lightFrom, circle, @lightColor, rgba(255, 255, 255, 0) @lightRadius*.7);
  }
  40%{
    background: -webkit-radial-gradient(50% 8*@section+@lightFrom, circle, @lightColor, rgba(255, 255, 255, 0) @lightRadius*.8);
  }
  45%{
    background: -webkit-radial-gradient(50% 9*@section+@lightFrom, circle, @lightColor, rgba(255, 255, 255, 0) @lightRadius*.9);
  }
  50%{
    background: -webkit-radial-gradient(50% 10*@section+@lightFrom, circle, @lightColor, rgba(255, 255, 255, 0) @lightRadius*1);
  }
  55%{
    background: -webkit-radial-gradient(50% 11*@section+@lightFrom, circle, @lightColor, rgba(255, 255, 255, 0) @lightRadius*.9);
  }
  60%{
    background: -webkit-radial-gradient(50% 12*@section+@lightFrom, circle, @lightColor, rgba(255, 255, 255, 0) @lightRadius*.8);
  }
  65%{
    background: -webkit-radial-gradient(50% 13*@section+@lightFrom, circle, @lightColor, rgba(255, 255, 255, 0) @lightRadius*.7);
  }
  70%{
    background: -webkit-radial-gradient(50% 14*@section+@lightFrom, circle, @lightColor, rgba(255, 255, 255, 0) @lightRadius*.6);
  }
  75%{
    background: -webkit-radial-gradient(50% 15*@section+@lightFrom, circle, @lightColor, rgba(255, 255, 255, 0) @lightRadius*.5);
  }
  80%{
    background: -webkit-radial-gradient(50% 16*@section+@lightFrom, circle, @lightColor, rgba(255, 255, 255, 0) @lightRadius*.4);
  }
  85%{
    background: -webkit-radial-gradient(50% 17*@section+@lightFrom, circle, @lightColor, rgba(255, 255, 255, 0) @lightRadius*.3);
  }
  90%{
    background: -webkit-radial-gradient(50% 18*@section+@lightFrom, circle, @lightColor, rgba(255, 255, 255, 0) @lightRadius*.2);
  }
  95%{
    background: -webkit-radial-gradient(50% 19*@section+@lightFrom, circle, @lightColor, rgba(255, 255, 255, 0) @lightRadius*.1);
  }
  100%{
    background: -webkit-radial-gradient(50% 20*@section+@lightFrom, circle, @lightColor, rgba(255, 255, 255, 0) @lightRadius*0);
  }
}

.flash-anim{
  animation: flash-anim .5s 1;
}


```

----

**after  css-nano - postcss-minify-gradients**

Please notice the diff the value greater than `25%`, the final value decreases to 0，it`s so weird.

----

```css
@keyframes flash-anim {
  0% {
    background: -webkit-radial-gradient(50% -10%,circle,#fff,hsla(0,0%,100%,0) 0);
  }

  5% {
    background: -webkit-radial-gradient(50% -4%,circle,#fff,hsla(0,0%,100%,0) 4%);
  }

  10% {
    background: -webkit-radial-gradient(50% 2%,circle,#fff,hsla(0,0%,100%,0) 8%);
  }

  15% {
    background: -webkit-radial-gradient(50% 8%,circle,#fff,hsla(0,0%,100%,0) 12%);
  }

  20% {
    background: -webkit-radial-gradient(50% 14%,circle,#fff,hsla(0,0%,100%,0) 16%);
  }


  30% {
    background: -webkit-radial-gradient(50% 26%,circle,#fff,hsla(0,0%,100%,0) 0);
  }

  35% {
    background: -webkit-radial-gradient(50% 32%,circle,#fff,hsla(0,0%,100%,0) 0);
  }

  40% {
    background: -webkit-radial-gradient(50% 38%,circle,#fff,hsla(0,0%,100%,0) 0);
  }

  45% {
    background: -webkit-radial-gradient(50% 44%,circle,#fff,hsla(0,0%,100%,0) 0);
  }

  50% {
    background: -webkit-radial-gradient(50% 50%,circle,#fff,hsla(0,0%,100%,0) 0);
  }

  55% {
    background: -webkit-radial-gradient(50% 56%,circle,#fff,hsla(0,0%,100%,0) 0);
  }

  60% {
    background: -webkit-radial-gradient(50% 62%,circle,#fff,hsla(0,0%,100%,0) 0);
  }

  65% {
    background: -webkit-radial-gradient(50% 68%,circle,#fff,hsla(0,0%,100%,0) 0);
  }

  70% {
    background: -webkit-radial-gradient(50% 74%,circle,#fff,hsla(0,0%,100%,0) 0);
  }

  75% {
    background: -webkit-radial-gradient(50% 80%,circle,#fff,hsla(0,0%,100%,0) 0);
  }

  80% {
    background: -webkit-radial-gradient(50% 86%,circle,#fff,hsla(0,0%,100%,0) 0);
  }

  85% {
    background: -webkit-radial-gradient(50% 92%,circle,#fff,hsla(0,0%,100%,0) 0);
  }

  90% {
    background: -webkit-radial-gradient(50% 98%,circle,#fff,hsla(0,0%,100%,0) 0);
  }

  95% {
    background: -webkit-radial-gradient(50% 104%,circle,#fff,hsla(0,0%,100%,0) 0);
  }

  to {
    background: -webkit-radial-gradient(50% 110%,circle,#fff,hsla(0,0%,100%,0) 0);
  }
}

.flash-anim {
  animation: flash-anim .5s 1;
}
```

----

The solution now I could offer is to disable the `postcss-minify-gradients`.

Setting css-loader minimize  an option  `postcss-minify-gradients` to false.

Like `minimize: { postcss-minify-gradients: false }`
