### ISSUE TITLE
Wrong minification on invalid input

### ISSUE THREAD

**Issue by felixmosh** [ben-eb/cssnano#402]
Hi,

I have custom strings inside my css, 
```css
body { border: "unit(--borderWidth, px)" solid "color(color-1)"; }
```
CSS-Nano removes the strings after minification, and it becomes
```css
body{border:solid}
```

I`ve tried, and if the input is only:
```css
body { border-width: "unit(--borderWidth, px)"; }
```
The output will remain that string.
```css
body{border-width:"unit(--borderWidth, px)"}
```

Expected result, those css strings should remain at the minified result.
