### ISSUE TITLE
mergeRules incorrectly merges placeholder selectors

### ISSUE THREAD

**Issue by maxlapides** [ben-eb/cssnano#419]
For example, consider this CSS file:

```css
input:-ms-input-placeholder {
  font-size: 14px;
}
input::-ms-input-placeholder {
  font-size: 14px;
}
```

If you run cssnano against this file with the default preset, you get:

```css
input:-ms-input-placeholder,input::-ms-input-placeholder{font-size:14px}
```

Unfortunately, this won't work with Internet Explorer. These rules cannot be safely merged. When I disable the `mergeRules` optimization, this issue is resolved.

This issue may be related to https://github.com/ben-eb/cssnano/issues/297
