### ISSUE TITLE
mergeLonghand not safe with custom properties

### ISSUE THREAD

**Issue by gillisandrew** [ben-eb/cssnano#450]
Input:
```css
:root {
  --my-personal-border-width: 2px;
  --my-personal-border-style: solid;
  --my-personal-border-color: #fff;
}
```
Output:
```css
:root{border:2px solid #fff}
```
Expected:
```css
:root{--my-personal-border-width:2px;--my-personal-border-style:solid;--my-personal-border-color:#fff}
```
