### ISSUE TITLE
Remove leading and trailing spaces in grid area definitions

### ISSUE THREAD

**Issue by jhpratt** [ben-eb/cssnano#460]
Input:

```css
foo {
  grid-template-areas: ' foo bar '
                       ' baz qux ';
}
```

Output: `foo{grid-template-areas:' a b ' ' c d '}`

Expected output: `foo{grid-template-areas:'a b' 'c d'}`

Basically, the leading and trailing whitespace inside the quotes is entirely useless, and should be removed.
