### ISSUE TITLE
Cutting off the end of calc

### ISSUE THREAD

**Issue by jv-PintoBobcat** [ben-eb/cssnano#48]
This is a new regression from 2.2.0 to 2.3.0.

Given this input css:

```css
.file-path-input.invalid {
  margin: 1px 1px calc(0.5em + 1px);
}
```

2.2.0 outputs this:
```css
.file-path-input.invalid{margin:1px 1px calc(.5em + 1px)}
```

2.3.0 outputs this:
```css
.file-path-input.invalid{margin:1px 1px calc(.5em +}
```

You can see that the 2.3.0 output is stripping the second half of the calc statement.
