### ISSUE TITLE
Support multiple values merge

### ISSUE THREAD

**Issue by yisibl** [ben-eb/cssnano#49]
input:

```css
h1 {
    border: 1px solid red;
    background-color: red;
    background-position: 50% 100%;
}

h1 {
    border: 1px #f00 solid;
    background-color: #f00;
    background-position: center bottom;
}

h1 {
    border: solid 1px rgb(255, 0, 0);
}
```

output:
```css
h1 {
    border: 1px solid red;
    background-color: red;
    background-position: 50% 100%;
}
```

**Comment by cedriceberhardt** [comment]
Would be cool to do the same with media queries.

**Comment by RoberMac** [comment]
@cedriceberhardt use [node-css-mqpacker](https://github.com/hail2u/node-css-mqpacker)

**Comment by cedriceberhardt** [comment]
Thanks @RoberMac  :+1:

**Comment by Kn4ppster** [comment]
Media query merging would be a great feature. Then I could remove some old packages from my gulpfile.

**Comment by marcobiedermann** [comment]
:+1: for multiple media queries. Saves a lot of bytes!

**Comment by antoniocapuozzo** [comment]
I'd love this, it'll let me remove some "unnecessary" packages

**Comment by ben-eb** [comment]
I'm going to close this as the behaviour is almost taken care of, and we have two other open issues that track the behaviour that is not yet implemented. As of writing, the original example is compressed to:

```css
h1{border:1px solid red;background-color:red;background-position:50% 100%;background-position:bottom}
```

* We have an open issue for declaration merging, here: https://github.com/ben-eb/cssnano/issues/86
* We also have an open issue for media query merging, here: https://github.com/ben-eb/cssnano/issues/111

So, ideally this will be merged to this once the declaration merging is resolved:

```css
h1{border:1px solid red;background-color:red;background-position:bottom}
```
