### ISSUE TITLE
'TypeError: Cannot call method 'indexOf' of undefined' when uglifying CSS

### ISSUE THREAD

**Issue by lsdafjklsd** [ben-eb/cssnano#52]
I'm getting this error on a few of my CSS files when running `webpack -p`, something about uglifying the CSS. Anyone recognize an error like this, or can point me in the direction of a more detailed stack trace? I get the error on 7 out of 100 or so css files. Combed through the files and couldn't find any weird syntax stuff.

```
ERROR in ./~/css-loader!./~/cssnext-loader!./app/styles/index.css
TypeError: Cannot call method 'indexOf' of undefined
```

Any help would be greatly appreciated.

**Comment by ben-eb** [comment]
I'm not a webpack user, a full stack trace would be useful. Can you reproduce with cssnano standalone?

**Comment by timkelty** [comment]
I'm getting the same error compiling with gulp.

I'm just passing cssnano as plugin to gulp-postcss, I'm _not_ using `gulp-cssnano`
```
[15:20:45] 'build:css' errored after 677 ms
[15:20:45] TypeError in plugin 'gulp-postcss'
Message:
    Cannot read property 'indexOf' of undefined
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

**Comment by ben-eb** [comment]
@timkelty Would it be possible to get a full stack trace please?

**Comment by timkelty** [comment]
Seems to break on this bit of CSS (imported from https://github.com/suitcss/components-button)
```
.Button {
  background: transparent;
  border-color: var(--Button-border-color);
  border-style: solid;
  border-width: var(--Button-border-width);
  box-sizing: border-box; /* 2 */
  color: var(--Button-color); /* 3 */
  cursor: pointer;
  display: inline-block;
  font: var(--Button-font); /* 4 */
  line-height: normal; /* 5 */
  margin: 0;
}
```

If I get rid of the line comments (`/* 1 */`), no error.

**Comment by timkelty** [comment]
Futher testing: doesn't seem to be relate to `var()` stuff at all, seems to just be choking on those comments.

**Comment by ben-eb** [comment]
CLI seems fine to me.

```css
.Button{background:transparent;border:var(--Button-border-width) solid var(--Button-border-color);box-sizing:border-box;color:var(--Button-color);cursor:pointer;display:inline-block;font:var(--Button-font);line-height:normal;margin:0}
```

Would it be possible to share a small test case where the error can be reproduced?
