### ISSUE TITLE
Bad transformation

### ISSUE THREAD

**Issue by kentor** [ben-eb/cssnano#56]
Using cssnano 3.0.0. I have this css:

test.css
```css
body {
  background-image: linear-gradient(
    45deg,
    transparent 25%,
    rgba(255,255,255,.2) 25%,
    rgba(255,255,255,.2) 75%,
    transparent 75%,
    transparent
  ), linear-gradient(
    45deg,
    transparent 25%,
    rgba(255,255,255,.2) 25%,
    rgba(255,255,255,.2) 75%,
    transparent 75%,
    transparent
  );
}
```

```
$(npm bin)/cssnano < test.css
body{background-image:linear-gradient(45deg,transparent 25%,hsla(0,0%,100%,.2) 25%,hsla(0,0%,100%,.2) 75%,transparent 75%,transparent 25%,hsla(0,0%,100%,.2) 75%,transparent 75%,transparent),linear-gradient(45deg,transparent 25%,hsla(0,0%,100%,.2))}%
```

The second linear-gradient is missing a bunch of stuff. Expected:
```
body{background-image:linear-gradient(45deg,transparent 25%,hsla(0,0%,100%,.2) 25%,hsla(0,0%,100%,.2) 75%,transparent 75%,transparent 25%,hsla(0,0%,100%,.2) 75%,transparent 75%,transparent),linear-gradient(45deg,transparent 25%,hsla(0,0%,100%,.2) 25%,hsla(0,0%,100%,.2) 75%,transparent 75%,transparent 25%,hsla(0,0%,100%,.2) 75%,transparent 75%,transparent)}
```

```diff
-body{background-image:linear-gradient(45deg,transparent 25%,hsla(0,0%,100%,.2) 25%,hsla(0,0%,100%,.2) 75%,transparent 75%,transparent 25%,hsla(0,0%,100%,.2) 75%,transparent 75%,transparent),linear-gradient(45deg,transparent 25%,hsla(0,0%,100%,.2))}
+body{background-image:linear-gradient(45deg,transparent 25%,hsla(0,0%,100%,.2) 25%,hsla(0,0%,100%,.2) 75%,transparent 75%,transparent 25%,hsla(0,0%,100%,.2) 75%,transparent 75%,transparent),linear-gradient(45deg,transparent 25%,hsla(0,0%,100%,.2) 25%,hsla(0,0%,100%,.2) 75%,transparent 75%,transparent 25%,hsla(0,0%,100%,.2) 75%,transparent 75%,transparent)}
```
