### ISSUE TITLE
cutting @font-face declaration when after it aren't other rules

### ISSUE THREAD

**Issue by MonsJovis** [ben-eb/cssnano#58]
If after the @font-face declation there aren't other rules or declarations in a file, the @font-face declaration is cutted

```css
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('../fonts/glyphicons-halflings-regular.eot');
  src: url('../fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../fonts/glyphicons-halflings-regular.woff2') format('woff2'), url('../fonts/glyphicons-halflings-regular.woff') format('woff'), url('../fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```
