### ISSUE TITLE
Merges @-webkit-keyframes and @keyframes and removes @keyframes

### ISSUE THREAD

**Issue by gowravshekar** [ben-eb/cssnano#70]
Configuration

```javascript
nano({
    zindex: false,
    reduceIdents: false,
    autoprefixer: {
        browsers: supportedBrowsers,
        add: true
    }
})
```

Input

```css
@-webkit-keyframes scaleUp {
    0% { }
    100% { -webkit-transform: scale(1); }
}

@keyframes scaleUp {
    0% { }
    100% { -webkit-transform: scale(1); transform: scale(1); }
}
```

Output

```css
@-webkit-keyframes scaleUp{to{-webkit-transform:scale(1)}}
```

The bug is present in [mergeRules](https://github.com/ben-eb/postcss-merge-rules)

Adding `mergeRules: false` to the above configuration, generates the correct output as shown below:

```css
@-webkit-keyframes scaleUp{to{-webkit-transform:scale(1)}}@keyframes scaleUp{to{-webkit-transform:scale(1);transform:scale(1)}}
```

**Comment by ben-eb** [comment]
I can't reproduce. Latest version on the CLI:

```
$ cssnano --no-discardUnused
```

Results in:

```css
@-webkit-keyframes scaleUp{to{-webkit-transform:scale(1)}}@keyframes scaleUp{to{-webkit-transform:scale(1);transform:scale(1)}}
```
