### ISSUE TITLE
cssnano mangles value if multiline with comment inside

### ISSUE THREAD

**Issue by MadLittleMods** [ben-eb/cssnano#81]
I came across a very weird issue where when `cssnano` is enabled, it will stop other plugins from transforming the value.

The comment(`/* some comment */`) seems to be the messing with something as it works fine without it.

```js
postcss([
	simplevariables(),
	cssnano()
]);
```

Input:
```css
$color: #f00;

:root {
	box-shadow:
		inset 0 -10px 12px 0 $color,
		/* some comment */
		inset 0 0 5px 0 $color;
}
```

Expected:

```
:root {box-shadow: inset 0 -10px 12px 0 red,inset 0 0 5px 0 red}
```

Actual (wrong):
```
:root{box-shadow:inset 0 -10px 12px 0 $color,inset 0 0 5px 0 $color}
```
