### ISSUE TITLE
Shorthands

### ISSUE THREAD

**Issue by benjaminfunk** [ben-eb/cssnano#87]
Dont now which module produce following code:

Code
```css
fr-toolbar.fr-top
{
	border: 1px solid #E0E0E0;
	border-bottom: 0;
}
.fr-toolbar.fr-bottom
{
	border: 1px solid #E0E0E0;
	border-top: 0;
}
```

Result
```css
.fr-toolbar.fr-top
{
	border-bottom: 0;
}
.fr-toolbar.fr-top,
.fr-toolbar.fr-bottom
{
	border: 1px solid #E0E0E0;
}
.fr-toolbar.fr-bottom
{
	border-bottom: 0;
}
````

The problem ist that the order is wrong so the element still have a 4 side border instead of 3

Grunt, cssnano 3.3.2. Only zindex option is set to false

**Comment by ben-eb** [comment]
I can't reproduce; output using latest CLI:

```css
.fr-toolbar.fr-top{border:1px solid #e0e0e0;border-bottom:0}
```

**Comment by benjaminfunk** [comment]
I updatet the Cod above. Please check it again

**Comment by ben-eb** [comment]
With:

```css
.fr-toolbar.fr-top
{
    border: 1px solid #E0E0E0;
    border-bottom: 0;
}
.fr-toolbar.fr-bottom
{
    border: 1px solid #E0E0E0;
    border-top: 0;
}
```

Output:

```css
.fr-toolbar.fr-top{border:1px solid #e0e0e0;border-bottom:0}.fr-toolbar.fr-bottom{border:1px solid #e0e0e0;border-top:0}
```

**Comment by benjaminfunk** [comment]
I debugged it again and only the following code will produce the error

```
.dispendium-theme.fr-toolbar.fr-top
{
	border-radius: 0;
	background-clip: padding-box;
	box-shadow: none;
	border: 1px solid #E0E0E0;
	border-bottom: 0;
}
.dispendium-theme.fr-toolbar.fr-bottom
{
	border-radius: 0;
	background-clip: padding-box;
	box-shadow: none;
	border: 1px solid #E0E0E0;
	border-top: 0;
}
```

Output
```
.dispendium-theme.fr-toolbar.fr-top{border-bottom:0}.dispendium-theme.fr-toolbar.fr-bottom,.dispendium-theme.fr-toolbar.fr-top{border-radius:0;background-clip:padding-box;box-shadow:none;border:1px solid #e0e0e0}.dispendium-theme.fr-toolbar.fr-bottom{border-top:0}
```

If i remove background-clip it works fine -.-

**Comment by ben-eb** [comment]
Ah ok, got it. For now you can work around this by disabling rule merging (`--no-mergeRules` on the CLI, `mergeRules: false` in JS).

**Comment by jeromecoupe** [comment]
Same kind of bug "solved" by adding `mergeRules: false`. The merging caused massive problem with my CSS grid.

Sample code

```css
.grid
{
  list-style: none;
  margin: 0;
  padding: 0;
  margin-left: -2rem;
}

.grid__unit
{
  margin: 0;
  padding: 0;
  width: 100%;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  padding-left: 2rem;
  display: inline-block;
  vertical-align: top;
}
```

output with `mergeRules` activated

.grid
{
  list-style:none;
  margin-left:-2rem
}
.grid,.grid__unit
{
  margin:0;
  padding:0
}
.grid__unit
{
  width:100%;
  box-sizing:border-box;
  padding-left:2rem;
  display:inline-block;
  vertical-align:top
}

which is obviously not a desirable side effect.
