### ISSUE TITLE
Lost vendor prefixes

### ISSUE THREAD

**Issue by 5lava** [ben-eb/cssnano#89]
I have following simple CSS code:
```css
#foo { animation-name: some-animation }
@keyframes some-animation {
	100% { transform: scale(2) }
}
```

Then I pass it through autoprefixer (no cssnano is involved at this moment):
```css
#foo {
	-webkit-animation-name: some-animation;
	-moz-animation-name:    some-animation;
	-o-animation-name:      some-animation;
	animation-name:         some-animation;
}
@-webkit-keyframes some-animation {
	100% {
		-webkit-transform: scale(2);
		transform:         scale(2);
	}
}
@-moz-keyframes some-animation {
	100% {
		-moz-transform: scale(2);
		transform:      scale(2);
	}
}
@-o-keyframes some-animation {
	100% {
		-o-transform: scale(2);
		transform:    scale(2);
	}
}
@keyframes some-animation {
	100% {
		-webkit-transform: scale(2);
		-moz-transform:    scale(2);
		-o-transform:      scale(2);
		transform:         scale(2);
	}
}
```

Finally, I pass this code to cssnano 3.3.2 with disabled autoprefixer (using cli or postcss or any other way, doesn't matter):
```
cssnano source.css --no-autoprefixer
```
```css
#foo {
	-webkit-animation-name: a;
	-moz-animation-name:    a;
	-o-animation-name:      a;
	animation-name:         a
}
@-webkit-keyframes a {
	to {
		-webkit-transform: scale(2);
		transform:         scale(2);
		-moz-transform:    scale(2);
		-o-transform:      scale(2)
	}
}
```
Boom, most vendor prefixes are gone.

**Comment by 5lava** [comment]
Here's another interesting example.
```css
#foo { animation-name: one }
#bar { animation-name: two }
@keyframes one {
	100% { transform: scale(1) }
}
@keyframes two {
/*	50% { transform: scale(5) }  --- this line is commented out! */
	100% { transform: scale(2) }
}
```
Step 1 (autoprefixer):
```css
#foo {
    -webkit-animation-name: one;
       -moz-animation-name: one;
         -o-animation-name: one;
            animation-name: one;
}
#bar {
    -webkit-animation-name: two;
       -moz-animation-name: two;
         -o-animation-name: two;
            animation-name: two;
}
@-webkit-keyframes one {
    100% {
        -webkit-transform: scale(1);
                transform: scale(1);
    }
}
@-moz-keyframes one {
    100% {
        -moz-transform: scale(1);
             transform: scale(1);
    }
}
@-o-keyframes one {
    100% {
        -o-transform: scale(1);
           transform: scale(1);
    }
}
@keyframes one {
    100% {
        -webkit-transform: scale(1);
           -moz-transform: scale(1);
             -o-transform: scale(1);
                transform: scale(1);
    }
}
@-webkit-keyframes two {
    100% {
        -webkit-transform: scale(2);
                transform: scale(2);
    }
}
@-moz-keyframes two {
    100% {
        -moz-transform: scale(2);
             transform: scale(2);
    }
}
@-o-keyframes two {
    100% {
        -o-transform: scale(2);
           transform: scale(2);
    }
}
@keyframes two {
    100% {
        -webkit-transform: scale(2);
           -moz-transform: scale(2);
             -o-transform: scale(2);
                transform: scale(2);
    }
}
```
Step 2, cssnano (autoprefixer disabled):
```css
#foo {
    -webkit-animation-name: a;
    -moz-animation-name: a;
    -o-animation-name: a;
    animation-name: a
}
#bar {
    -webkit-animation-name: b;
    -moz-animation-name: b;
    -o-animation-name: b;
    animation-name: b
}
@-webkit-keyframes a {
    to {
        -webkit-transform: scale(1);
        transform: scale(1);
        -moz-transform: scale(1);
        -o-transform: scale(1)
    }
}
@-webkit-keyframes b {
    to {
        -webkit-transform: scale(2);
        transform: scale(2);
        -moz-transform: scale(2);
        -o-transform: scale(2)
    }
}
```
Pretty much the same problem as in my first example. Now let's uncomment that line:
```css
#foo { animation-name: one }
#bar { animation-name: two }
@keyframes one {
	100% { transform: scale(1) }
}
@keyframes two {
	50% { transform: scale(2) }  /* uncommented line */
	100% { transform: scale(2) }
}
```
After step 1:
```css
#foo {
    -webkit-animation-name: one;
       -moz-animation-name: one;
         -o-animation-name: one;
            animation-name: one;
}
#bar {
    -webkit-animation-name: two;
       -moz-animation-name: two;
         -o-animation-name: two;
            animation-name: two;
}
@-webkit-keyframes one {
    100% {
        -webkit-transform: scale(1);
                transform: scale(1);
    }
}
@-moz-keyframes one {
    100% {
        -moz-transform: scale(1);
             transform: scale(1);
    }
}
@-o-keyframes one {
    100% {
        -o-transform: scale(1);
           transform: scale(1);
    }
}
@keyframes one {
    100% {
        -webkit-transform: scale(1);
           -moz-transform: scale(1);
             -o-transform: scale(1);
                transform: scale(1);
    }
}
@-webkit-keyframes two {
    50% {
        -webkit-transform: scale(5);
                transform: scale(5);
    }
    100% {
        -webkit-transform: scale(2);
                transform: scale(2);
    }
}
@-moz-keyframes two {
    50% {
        -moz-transform: scale(5);
             transform: scale(5);
    }
    100% {
        -moz-transform: scale(2);
             transform: scale(2);
    }
}
@-o-keyframes two {
    50% {
        -o-transform: scale(5);
           transform: scale(5);
    }
    100% {
        -o-transform: scale(2);
           transform: scale(2);
    }
}
@keyframes two {
    50% {
        -webkit-transform: scale(5);
           -moz-transform: scale(5);
             -o-transform: scale(5);
                transform: scale(5);
    }
    100% {
        -webkit-transform: scale(2);
           -moz-transform: scale(2);
             -o-transform: scale(2);
                transform: scale(2);
    }
}
```
After step 2:
```css
#foo {
    -webkit-animation-name: a;
    -moz-animation-name: a;
    -o-animation-name: a;
    animation-name: a
}
#bar {
    -webkit-animation-name: b;
    -moz-animation-name: b;
    -o-animation-name: b;
    animation-name: b
}
@-webkit-keyframes a {
    to {
        -webkit-transform: scale(1);
        transform: scale(1);
        -moz-transform: scale(1);
        -o-transform: scale(1)
    }
}
@-webkit-keyframes b {
    50% {
        -webkit-transform: scale(5);
        transform: scale(5)
    }
    to {
        -webkit-transform: scale(2);
        transform: scale(2)
    }
}
@-moz-keyframes b {
    50% {
        -moz-transform: scale(5);
        transform: scale(5)
    }
    to {
        -moz-transform: scale(2);
        transform: scale(2)
    }
}
@-o-keyframes b {
    50% {
        -o-transform: scale(5);
        transform: scale(5)
    }
    to {
        -o-transform: scale(2);
        transform: scale(2)
    }
}
@keyframes b {
    50% {
        -webkit-transform: scale(5);
        -moz-transform: scale(5);
        -o-transform: scale(5);
        transform: scale(5)
    }
    to {
        -webkit-transform: scale(2);
        -moz-transform: scale(2);
        -o-transform: scale(2);
        transform: scale(2)
    }
}
```
Looks like the bug appeared only on animation `a` (originally `one`), but animation `b` (originally `two`) was processed correctly.
