### ISSUE TITLE
Option for rounding values?

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/cssnano#93]
Input:

```css
div {
  right: 6.66667px
}
```

Output:

```css
div {
  right: 6.67px
}
```

With customisable precision (you could specify `0` to get `7` rather than `6.67`). Thoughts?
