### ISSUE TITLE
Keep line breaks option similar to clean-css

### ISSUE THREAD

**Issue by madastro** [ben-eb/cssnano#96]
Is there a keep-line-break option in cssnano / gulp-cssnano similar to clean-css / gulp-minify-css?

**Comment by TrySound** [comment]
@madastro You can disable `core` plugin

**Comment by madastro** [comment]
Thanks @TrySound, tried but not the output I expected, was wondering if I could get something like this:
```css
html { font-family: sans-serif; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; }
body { margin: 0; }
article, aside, details, figcaption, figure, footer, header, hgroup, main, menu, nav, section, summary { display: block; }
audio, canvas, progress, video { display: inline-block; vertical-align: baseline; }
```
sorry should have specified that earlier.
