### ISSUE TITLE
TypeError in plugin 'gulp-postcss'

### ISSUE THREAD

**Issue by msfragala** [ben-eb/cssnano#99]
I am using `cssnano` as a plugin for `gulp-postcss` and am running into the following error.
```
Message:
    Cannot read property 'type' of undefined
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```
Sometimes it can't read property `node` of `undefined`. I did see #52, but couldn't find anything helpful there. I'm not using any line comments, like were throwing things off there. I'm only testing the Gulp build, so the CSS file is very simplistic:
```
@import './*.css'; //fails regardless of this import
*  {
  size: 12px 12px;
}
```
